import {Role} from "components/user/user.interface";

export const GROUP_INVENTORY: Role[] = [
  Role.INVENTORY_PROCUREMENT_INITIATOR,
  Role.INVENTORY_PROCUREMENT_VERIFIER,
  Role.INVENTORY_PROCUREMENT_AUDITOR,
  Role.INVENTORY_PROCUREMENT_APPROVER,
  Role.INVENTORY_PROCUREMENT_EC,
  Role.INVENTORY_PROCUREMENT_FINANCE_APPROVER,
  Role.INVENTORY_RECEIVE_INITIATOR,
  Role.INVENTORY_RECEIVE_VERIFIER,
  Role.INVENTORY_RECEIVE_APPROVER,
  Role.INVENTORY_RECEIVE_AUDITOR,
  Role.INVENTORY_TRANSFER_INITIATOR,
  Role.INVENTORY_TRANSFER_VERIFIER,
  Role.INVENTORY_TRANSFER_AUDITOR,
  Role.INVENTORY_TRANSFER_APPROVER,
  
];

export const GROUP_IDENTITY_MANAGEMENT: Role[] = [
  Role.identity_indv_list,
  Role.identity_corp_list,
  Role.identity_agent_list,
];
export const GROUP_USER_MANAGEMENT: Role[] = [
  Role.user_update,
  Role.user_view,
  Role.user_list,
  Role.user_new,
  Role.user_password,
  Role.user_login,
];
export const GROUP_PERMISSION_MANAGEMENT: Role[] = [
  Role.group_permission_list,
  Role.group_permission_remove,
  Role.group_permission_add,
  Role.group_create,
];
export const GROUP_COLLECTION: Role[] = [
  Role.collection_view,
];

export const GROUP_INVENTORY_PROCUREMENT: Role[] = [
  Role.INVENTORY_PROCUREMENT_INITIATOR,
  Role.INVENTORY_PROCUREMENT_VERIFIER,
  Role.INVENTORY_PROCUREMENT_AUDITOR,
  Role.INVENTORY_PROCUREMENT_APPROVER,
  Role.INVENTORY_PROCUREMENT_EC,
  Role.INVENTORY_PROCUREMENT_FINANCE_APPROVER,
];

export const GROUP_INVENTORY_TRANSFER: Role[] = [
  Role.INVENTORY_TRANSFER_INITIATOR,
  Role.INVENTORY_TRANSFER_VERIFIER,
  Role.INVENTORY_TRANSFER_AUDITOR,
  Role.INVENTORY_TRANSFER_APPROVER,
];

export const GROUP_INVENTORY_RECEIVE: Role[] = [
  Role.INVENTORY_RECEIVE_INITIATOR,
  Role.INVENTORY_RECEIVE_VERIFIER,
  Role.INVENTORY_RECEIVE_APPROVER,
  Role.INVENTORY_RECEIVE_AUDITOR,
];

export const GROUP_VEHICLE_LICENCE_CAPTURE: Role[] = [
  Role.VEHICLE_LICENCE_CAPTURE_INITIATOR,
  Role.VEHICLE_LICENCE_CAPTURE_VERIFIER,
  Role.VEHICLE_LICENCE_CAPTURE_APPROVER,
];
export const GROUP_CHANGE_OF_OWNERSHIP_CAPTURE: Role[] = [
  Role.VEHICLE_CHANGE_OF_OWNERSHIP_CAPTURE_INITIATOR,
  Role.VEHICLE_CHANGE_OF_OWNERSHIP_CAPTURE_VERIFIER,
  Role.VEHICLE_CHANGE_OF_OWNERSHIP_CAPTURE_APPROVER,
];

export const GROUP_INVENTORY_REPORT = [
  Role.INVENTORY_REPORT_INITIATOR,
  Role.INVENTORY_REPORT_VERIFIER,
  Role.INVENTORY_REPORT_APPROVER,
];
